### ISSUE TITLE
Error while sending QUERY packet

### ISSUE THREAD

**Issue by msaus** [duncan3dc/fork-helper#8]
Hello there,

I am getting following error when I insert data into MySQL db.

Error while sending QUERY packet. PID=15521 with query: "INSERT INTO....

Do you know how to solve this issue?

**Comment by msaus** [comment]
I am using fuelPHP ORM to insert data.

**Comment by msaus** [comment]
Possibly, the connection to mysql is disconnected after the fork wait().

**Comment by duncan3dc** [comment]
Hi @msaus, yes this is a common problem with threading. Once one thread finishes PHP cleans up any resources in use, which includes MySQL connections.
The way to avoid it is to create a brand new connection inside each thread, rather than sharing an existing one.
Let me know if that's not clear and I'll post some example code. Good luck!

**Comment by msaus** [comment]
Thank you :)
